/** Chapter 3 Practice Quiz — Set 1 + Set 2 (50 questions) */
window.QUIZ_QUESTIONS = [
  // —— Set 1 ——
  {
    id: 1,
    topic: "Fractions & Decimals",
    prompt: "Write as a decimal. Use bar notation if needed.",
    question: "\\dfrac{7}{9}",
    choices: [
      { text: "0.\\overline{7}", correct: true },
      { text: "0.79", correct: false },
      { text: "0.7", correct: false },
      { text: "0.\\overline{79}", correct: false },
    ],
    explain: "\\(7 \\div 9 = 0.777\\ldots\\), written as \\(0.\\overline{7}\\).",
  },
  {
    id: 2,
    topic: "Fractions & Decimals",
    prompt: "Write as a decimal.",
    question: "2\\dfrac{3}{8}",
    choices: [
      { text: "2.38", correct: false },
      { text: "2.375", correct: true },
      { text: "2.3\\overline{8}", correct: false },
      { text: "2.83", correct: false },
    ],
    explain: "\\(\\dfrac{3}{8} = 0.375\\), so \\(2\\dfrac{3}{8} = 2.375\\).",
  },
  {
    id: 3,
    topic: "Fractions & Decimals",
    prompt: "Write as a fraction in simplest form.",
    question: "0.45",
    choices: [
      { text: "\\dfrac{45}{100}", correct: false },
      { text: "\\dfrac{9}{20}", correct: true },
      { text: "\\dfrac{4}{5}", correct: false },
      { text: "\\dfrac{45}{99}", correct: false },
    ],
    explain: "\\(0.45 = \\dfrac{45}{100} = \\dfrac{9}{20}\\).",
  },
  {
    id: 4,
    topic: "Fractions & Decimals",
    prompt: "Write as a mixed number in simplest form.",
    question: "3.75",
    choices: [
      { text: "3\\dfrac{75}{100}", correct: false },
      { text: "3\\dfrac{3}{4}", correct: true },
      { text: "\\dfrac{15}{4}", correct: false },
      { text: "3\\dfrac{7}{5}", correct: false },
    ],
    explain: "\\(0.75 = \\dfrac{3}{4}\\), so \\(3.75 = 3\\dfrac{3}{4}\\).",
  },
  {
    id: 5,
    topic: "Compare Numbers",
    prompt: "Write <, >, or =.",
    question: "\\dfrac{5}{8}\\quad\\_\\_\\_\\quad 0.60",
    choices: [
      { text: "<", correct: false },
      { text: ">", correct: true },
      { text: "=", correct: false },
      { text: "Cannot tell", correct: false },
    ],
    explain: "\\(\\dfrac{5}{8} = 0.625\\), and \\(0.625 > 0.60\\).",
  },
  {
    id: 6,
    topic: "Compare Numbers",
    prompt: "Write <, >, or =.",
    question: "1\\dfrac{2}{5}\\quad\\_\\_\\_\\quad 1.42",
    choices: [
      { text: "<", correct: true },
      { text: ">", correct: false },
      { text: "=", correct: false },
      { text: "Cannot tell", correct: false },
    ],
    explain: "\\(1\\dfrac{2}{5} = 1.4\\), and \\(1.4 < 1.42\\).",
  },
  {
    id: 7,
    topic: "True or False",
    prompt: "Determine whether the statement is true or false. If false, choose the best reason.",
    question: "\\(-8\\) is a whole number.",
    choices: [
      { text: "True", correct: false },
      { text: "False — whole numbers are \\(0, 1, 2, \\ldots\\); negatives are not included", correct: true },
      { text: "False — \\(-8\\) is not an integer", correct: false },
      { text: "False — \\(-8\\) is a rational number only", correct: false },
    ],
    explain: "Whole numbers are non-negative integers. \\(-8\\) is an integer, but not a whole number.",
  },
  {
    id: 8,
    topic: "True or False",
    prompt: "Determine whether the statement is true or false.",
    question: "Every whole number is an integer.",
    choices: [
      { text: "True", correct: true },
      { text: "False — whole numbers include fractions", correct: false },
      { text: "False — integers do not include zero", correct: false },
      { text: "False — only positive whole numbers are integers", correct: false },
    ],
    explain: "Whole numbers are \\(0, 1, 2, \\ldots\\), and all of these are integers.",
  },
  {
    id: 9,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "\\dfrac{4}{7}\\times\\left(-\\dfrac{14}{15}\\right)",
    choices: [
      { text: "-\\dfrac{8}{15}", correct: true },
      { text: "-\\dfrac{56}{105}", correct: false },
      { text: "\\dfrac{8}{15}", correct: false },
      { text: "-\\dfrac{2}{3}", correct: false },
    ],
    explain: "\\(\\dfrac{4}{7}\\times\\left(-\\dfrac{14}{15}\\right) = -\\dfrac{56}{105} = -\\dfrac{8}{15}\\).",
  },
  {
    id: 10,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "2\\dfrac{1}{4}\\times\\left(-1\\dfrac{1}{3}\\right)",
    choices: [
      { text: "-3", correct: true },
      { text: "-\\dfrac{9}{4}", correct: false },
      { text: "3", correct: false },
      { text: "-\\dfrac{3}{4}", correct: false },
    ],
    explain: "\\(\\dfrac{9}{4}\\times\\left(-\\dfrac{4}{3}\\right) = -3\\).",
  },
  {
    id: 11,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "-3\\dfrac{1}{2}\\times 2\\dfrac{2}{7}",
    choices: [
      { text: "-8", correct: true },
      { text: "-7", correct: false },
      { text: "8", correct: false },
      { text: "-\\dfrac{16}{2}", correct: false },
    ],
    explain: "\\(-\\dfrac{7}{2}\\times\\dfrac{16}{7} = -8\\).",
  },
  {
    id: 12,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "3\\dfrac{3}{4}\\div\\dfrac{5}{8}",
    choices: [
      { text: "6", correct: true },
      { text: "\\dfrac{15}{4}", correct: false },
      { text: "\\dfrac{24}{5}", correct: false },
      { text: "\\dfrac{5}{6}", correct: false },
    ],
    explain: "\\(\\dfrac{15}{4}\\times\\dfrac{8}{5} = 6\\).",
  },
  {
    id: 13,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "-2\\dfrac{2}{3}\\div 1\\dfrac{1}{3}",
    choices: [
      { text: "-2", correct: true },
      { text: "-\\dfrac{8}{3}", correct: false },
      { text: "2", correct: false },
      { text: "-\\dfrac{1}{2}", correct: false },
    ],
    explain: "\\(-\\dfrac{8}{3}\\div\\dfrac{4}{3} = -\\dfrac{8}{3}\\times\\dfrac{3}{4} = -2\\).",
  },
  {
    id: 14,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "\\dfrac{7}{12}\\div\\left(-\\dfrac{14}{9}\\right)",
    choices: [
      { text: "-\\dfrac{3}{8}", correct: true },
      { text: "-\\dfrac{7}{8}", correct: false },
      { text: "\\dfrac{3}{8}", correct: false },
      { text: "-\\dfrac{98}{108}", correct: false },
    ],
    explain: "\\(\\dfrac{7}{12}\\times\\left(-\\dfrac{9}{14}\\right) = -\\dfrac{3}{8}\\).",
  },
  {
    id: 15,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "-\\dfrac{3}{8}+\\left(-\\dfrac{5}{6}\\right)",
    choices: [
      { text: "-1\\dfrac{5}{24}", correct: true },
      { text: "-\\dfrac{8}{14}", correct: false },
      { text: "-\\dfrac{29}{48}", correct: false },
      { text: "\\dfrac{29}{24}", correct: false },
    ],
    explain: "LCD is 24: \\(-\\dfrac{9}{24}+\\left(-\\dfrac{20}{24}\\right)=-\\dfrac{29}{24}=-1\\dfrac{5}{24}\\).",
  },
  {
    id: 16,
    topic: "Add & Subtract",
    prompt: "Subtract. Simplify your answer.",
    question: "4\\dfrac{2}{5}-1\\dfrac{3}{10}",
    choices: [
      { text: "3\\dfrac{1}{10}", correct: true },
      { text: "3\\dfrac{1}{5}", correct: false },
      { text: "2\\dfrac{9}{10}", correct: false },
      { text: "3\\dfrac{5}{10}", correct: false },
    ],
    explain: "\\(\\dfrac{44}{10}-\\dfrac{13}{10}=\\dfrac{31}{10}=3\\dfrac{1}{10}\\).",
  },
  {
    id: 17,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "-3\\dfrac{1}{4}+2\\dfrac{2}{3}",
    choices: [
      { text: "-\\dfrac{7}{12}", correct: true },
      { text: "-\\dfrac{5}{12}", correct: false },
      { text: "\\dfrac{7}{12}", correct: false },
      { text: "-1\\dfrac{5}{12}", correct: false },
    ],
    explain: "\\(-\\dfrac{13}{4}+\\dfrac{8}{3}=-\\dfrac{39}{12}+\\dfrac{32}{12}=-\\dfrac{7}{12}\\).",
  },
  {
    id: 18,
    topic: "Add & Subtract",
    prompt: "Subtract. Simplify your answer.",
    question: "-2\\dfrac{5}{6}-3\\dfrac{1}{4}",
    choices: [
      { text: "-6\\dfrac{1}{12}", correct: true },
      { text: "-5\\dfrac{1}{12}", correct: false },
      { text: "-\\dfrac{73}{24}", correct: false },
      { text: "6\\dfrac{1}{12}", correct: false },
    ],
    explain: "\\(-\\dfrac{17}{6}-\\dfrac{13}{4}=-\\dfrac{34}{12}-\\dfrac{39}{12}=-\\dfrac{73}{12}=-6\\dfrac{1}{12}\\).",
  },
  {
    id: 19,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "5\\dfrac{3}{8}+\\left(-2\\dfrac{1}{2}\\right)",
    choices: [
      { text: "2\\dfrac{7}{8}", correct: true },
      { text: "3\\dfrac{1}{8}", correct: false },
      { text: "2\\dfrac{1}{8}", correct: false },
      { text: "7\\dfrac{7}{8}", correct: false },
    ],
    explain: "\\(\\dfrac{43}{8}-\\dfrac{20}{8}=\\dfrac{23}{8}=2\\dfrac{7}{8}\\).",
  },
  {
    id: 20,
    topic: "Simplest Form & Algebra",
    prompt: "Which is written in simplest form?",
    question: "",
    choices: [
      { text: "\\dfrac{18}{24}", correct: false },
      { text: "\\dfrac{14}{21}", correct: false },
      { text: "3\\dfrac{5}{8}", correct: true },
      { text: "\\dfrac{16}{20}", correct: false },
    ],
    explain: "A, B, and D can all be reduced. \\(3\\dfrac{5}{8}\\) is already simplest.",
  },
  {
    id: 21,
    topic: "Simplest Form & Algebra",
    prompt: "Simplify:",
    question: "\\dfrac{4}{x}\\div\\dfrac{8}{3x}",
    choices: [
      { text: "\\dfrac{3}{2}", correct: true },
      { text: "\\dfrac{1}{2}", correct: false },
      { text: "\\dfrac{32}{3x^{2}}", correct: false },
      { text: "\\dfrac{3x}{2}", correct: false },
    ],
    explain: "\\(\\dfrac{4}{x}\\times\\dfrac{3x}{8}=\\dfrac{12x}{8x}=\\dfrac{3}{2}\\) (for \\(x\\neq 0\\)).",
  },
  {
    id: 22,
    topic: "Simplest Form & Algebra",
    prompt: "Translate into an algebraic expression:",
    question: "Five more than the product of negative three and a number.",
    choices: [
      { text: "-3x + 5", correct: true },
      { text: "5 - 3 + x", correct: false },
      { text: "-3(x + 5)", correct: false },
      { text: "5x - 3", correct: false },
    ],
    explain: "Product of \\(-3\\) and a number is \\(-3x\\); five more than that is \\(-3x+5\\).",
  },
  {
    id: 23,
    topic: "Simplest Form & Algebra",
    prompt: "Evaluate \\(2x - 3y\\) when \\(x = -4\\) and \\(y = 2\\).",
    question: "",
    choices: [
      { text: "-14", correct: true },
      { text: "-2", correct: false },
      { text: "2", correct: false },
      { text: "-10", correct: false },
    ],
    explain: "\\(2(-4) - 3(2) = -8 - 6 = -14\\).",
  },
  {
    id: 24,
    topic: "Word Problem",
    prompt: "A recipe requires \\(\\dfrac{3}{4}\\) cup of sugar for one batch. If you make 3 batches, how many cups of sugar are needed?",
    question: "",
    choices: [
      { text: "2\\dfrac{1}{4} cups", correct: true },
      { text: "\\dfrac{3}{4} cups", correct: false },
      { text: "3\\dfrac{3}{4} cups", correct: false },
      { text: "\\dfrac{9}{12} cups", correct: false },
    ],
    explain: "\\(\\dfrac{3}{4}\\times 3 = \\dfrac{9}{4} = 2\\dfrac{1}{4}\\) cups.",
  },
  {
    id: 25,
    topic: "Word Problem",
    prompt: "A runner runs \\(2\\dfrac{1}{2}\\) miles each day for 4 days. How many miles does the runner run altogether?",
    question: "",
    choices: [
      { text: "10 miles", correct: true },
      { text: "6\\dfrac{1}{2} miles", correct: false },
      { text: "8 miles", correct: false },
      { text: "\\dfrac{5}{2} miles", correct: false },
    ],
    explain: "\\(2\\dfrac{1}{2}\\times 4 = \\dfrac{5}{2}\\times 4 = 10\\) miles.",
  },

  // —— Set 2 (easier review) ——
  {
    id: 26,
    topic: "Fractions & Decimals",
    prompt: "Write as a decimal.",
    question: "\\dfrac{3}{4}",
    choices: [
      { text: "0.34", correct: false },
      { text: "0.75", correct: true },
      { text: "0.7", correct: false },
      { text: "0.43", correct: false },
    ],
    explain: "\\(3 \\div 4 = 0.75\\).",
  },
  {
    id: 27,
    topic: "Fractions & Decimals",
    prompt: "Write as a decimal.",
    question: "1\\dfrac{1}{2}",
    choices: [
      { text: "1.2", correct: false },
      { text: "1.5", correct: true },
      { text: "1.12", correct: false },
      { text: "0.5", correct: false },
    ],
    explain: "\\(\\dfrac{1}{2} = 0.5\\), so \\(1\\dfrac{1}{2} = 1.5\\).",
  },
  {
    id: 28,
    topic: "Fractions & Decimals",
    prompt: "Write as a fraction in simplest form.",
    question: "0.6",
    choices: [
      { text: "\\dfrac{6}{10}", correct: false },
      { text: "\\dfrac{3}{5}", correct: true },
      { text: "\\dfrac{6}{9}", correct: false },
      { text: "\\dfrac{2}{5}", correct: false },
    ],
    explain: "\\(0.6 = \\dfrac{6}{10} = \\dfrac{3}{5}\\).",
  },
  {
    id: 29,
    topic: "Fractions & Decimals",
    prompt: "Write as a mixed number in simplest form.",
    question: "2.5",
    choices: [
      { text: "2\\dfrac{5}{10}", correct: false },
      { text: "2\\dfrac{1}{2}", correct: true },
      { text: "\\dfrac{5}{2}", correct: false },
      { text: "2\\dfrac{1}{5}", correct: false },
    ],
    explain: "\\(0.5 = \\dfrac{1}{2}\\), so \\(2.5 = 2\\dfrac{1}{2}\\).",
  },
  {
    id: 30,
    topic: "Compare Numbers",
    prompt: "Write <, >, or =.",
    question: "\\dfrac{1}{2}\\quad\\_\\_\\_\\quad 0.4",
    choices: [
      { text: "<", correct: false },
      { text: ">", correct: true },
      { text: "=", correct: false },
      { text: "Cannot tell", correct: false },
    ],
    explain: "\\(\\dfrac{1}{2} = 0.5\\), and \\(0.5 > 0.4\\).",
  },
  {
    id: 31,
    topic: "Compare Numbers",
    prompt: "Write <, >, or =.",
    question: "\\dfrac{3}{4}\\quad\\_\\_\\_\\quad 0.75",
    choices: [
      { text: "<", correct: false },
      { text: ">", correct: false },
      { text: "=", correct: true },
      { text: "Cannot tell", correct: false },
    ],
    explain: "\\(\\dfrac{3}{4} = 0.75\\).",
  },
  {
    id: 32,
    topic: "True or False",
    prompt: "Determine whether the statement is true or false. If false, choose the best reason.",
    question: "\\(-3\\) is an integer.",
    choices: [
      { text: "True", correct: true },
      { text: "False — integers cannot be negative", correct: false },
      { text: "False — \\(-3\\) is only a whole number", correct: false },
      { text: "False — \\(-3\\) is a decimal", correct: false },
    ],
    explain: "Integers include ..., \\(-2\\), \\(-1\\), \\(0\\), \\(1\\), \\(2\\), .... So \\(-3\\) is an integer.",
  },
  {
    id: 33,
    topic: "True or False",
    prompt: "Determine whether the statement is true or false.",
    question: "Every integer is a whole number.",
    choices: [
      { text: "True", correct: false },
      { text: "False — negative integers are not whole numbers", correct: true },
      { text: "False — zero is not an integer", correct: false },
      { text: "False — whole numbers include fractions", correct: false },
    ],
    explain: "Whole numbers are \\(0, 1, 2, \\ldots\\). Negative integers like \\(-1\\) are integers but not whole numbers.",
  },
  {
    id: 34,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "\\dfrac{2}{3}\\times\\dfrac{3}{4}",
    choices: [
      { text: "\\dfrac{1}{2}", correct: true },
      { text: "\\dfrac{6}{12}", correct: false },
      { text: "\\dfrac{5}{7}", correct: false },
      { text: "\\dfrac{2}{4}", correct: false },
    ],
    explain: "\\(\\dfrac{2}{3}\\times\\dfrac{3}{4} = \\dfrac{6}{12} = \\dfrac{1}{2}\\).",
  },
  {
    id: 35,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "\\dfrac{3}{5}\\times\\left(-\\dfrac{1}{3}\\right)",
    choices: [
      { text: "-\\dfrac{1}{5}", correct: true },
      { text: "-\\dfrac{3}{15}", correct: false },
      { text: "\\dfrac{1}{5}", correct: false },
      { text: "-\\dfrac{4}{8}", correct: false },
    ],
    explain: "\\(\\dfrac{3}{5}\\times\\left(-\\dfrac{1}{3}\\right) = -\\dfrac{3}{15} = -\\dfrac{1}{5}\\).",
  },
  {
    id: 36,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "1\\dfrac{1}{2}\\times 2",
    choices: [
      { text: "3", correct: true },
      { text: "2\\dfrac{1}{2}", correct: false },
      { text: "\\dfrac{3}{2}", correct: false },
      { text: "4", correct: false },
    ],
    explain: "\\(\\dfrac{3}{2}\\times 2 = 3\\).",
  },
  {
    id: 37,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "\\dfrac{3}{4}\\div\\dfrac{1}{2}",
    choices: [
      { text: "\\dfrac{3}{2}", correct: true },
      { text: "\\dfrac{3}{8}", correct: false },
      { text: "\\dfrac{1}{2}", correct: false },
      { text: "2", correct: false },
    ],
    explain: "\\(\\dfrac{3}{4}\\times\\dfrac{2}{1} = \\dfrac{6}{4} = \\dfrac{3}{2}\\).",
  },
  {
    id: 38,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "2\\div\\dfrac{1}{4}",
    choices: [
      { text: "8", correct: true },
      { text: "\\dfrac{1}{2}", correct: false },
      { text: "\\dfrac{1}{8}", correct: false },
      { text: "4", correct: false },
    ],
    explain: "\\(2\\times 4 = 8\\).",
  },
  {
    id: 39,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "-\\dfrac{4}{5}\\div\\dfrac{2}{5}",
    choices: [
      { text: "-2", correct: true },
      { text: "-\\dfrac{8}{25}", correct: false },
      { text: "2", correct: false },
      { text: "-\\dfrac{2}{5}", correct: false },
    ],
    explain: "\\(-\\dfrac{4}{5}\\times\\dfrac{5}{2} = -2\\).",
  },
  {
    id: 40,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "\\dfrac{1}{4}+\\dfrac{1}{2}",
    choices: [
      { text: "\\dfrac{3}{4}", correct: true },
      { text: "\\dfrac{2}{6}", correct: false },
      { text: "\\dfrac{1}{6}", correct: false },
      { text: "\\dfrac{1}{8}", correct: false },
    ],
    explain: "LCD is 4: \\(\\dfrac{1}{4}+\\dfrac{2}{4}=\\dfrac{3}{4}\\).",
  },
  {
    id: 41,
    topic: "Add & Subtract",
    prompt: "Subtract. Simplify your answer.",
    question: "\\dfrac{5}{6}-\\dfrac{1}{3}",
    choices: [
      { text: "\\dfrac{1}{2}", correct: true },
      { text: "\\dfrac{4}{3}", correct: false },
      { text: "\\dfrac{4}{6}", correct: false },
      { text: "\\dfrac{2}{3}", correct: false },
    ],
    explain: "LCD is 6: \\(\\dfrac{5}{6}-\\dfrac{2}{6}=\\dfrac{3}{6}=\\dfrac{1}{2}\\).",
  },
  {
    id: 42,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "-\\dfrac{2}{5}+\\dfrac{1}{5}",
    choices: [
      { text: "-\\dfrac{1}{5}", correct: true },
      { text: "-\\dfrac{3}{5}", correct: false },
      { text: "\\dfrac{1}{5}", correct: false },
      { text: "-\\dfrac{1}{10}", correct: false },
    ],
    explain: "Same denominator: \\(-\\dfrac{2}{5}+\\dfrac{1}{5}=-\\dfrac{1}{5}\\).",
  },
  {
    id: 43,
    topic: "Add & Subtract",
    prompt: "Subtract. Simplify your answer.",
    question: "3\\dfrac{1}{2}-1\\dfrac{1}{4}",
    choices: [
      { text: "2\\dfrac{1}{4}", correct: true },
      { text: "2\\dfrac{1}{2}", correct: false },
      { text: "4\\dfrac{3}{4}", correct: false },
      { text: "2\\dfrac{3}{4}", correct: false },
    ],
    explain: "\\(\\dfrac{7}{2}-\\dfrac{5}{4}=\\dfrac{14}{4}-\\dfrac{5}{4}=\\dfrac{9}{4}=2\\dfrac{1}{4}\\).",
  },
  {
    id: 44,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "2\\dfrac{1}{3}+1\\dfrac{1}{3}",
    choices: [
      { text: "3\\dfrac{2}{3}", correct: true },
      { text: "3\\dfrac{1}{3}", correct: false },
      { text: "4", correct: false },
      { text: "\\dfrac{10}{3}", correct: false },
    ],
    explain: "\\(\\dfrac{7}{3}+\\dfrac{4}{3}=\\dfrac{11}{3}=3\\dfrac{2}{3}\\).",
  },
  {
    id: 45,
    topic: "Simplest Form & Algebra",
    prompt: "Which is written in simplest form?",
    question: "",
    choices: [
      { text: "\\dfrac{4}{8}", correct: false },
      { text: "\\dfrac{6}{9}", correct: false },
      { text: "\\dfrac{2}{5}", correct: true },
      { text: "\\dfrac{10}{15}", correct: false },
    ],
    explain: "A, B, and D can all be reduced. \\(\\dfrac{2}{5}\\) is already simplest.",
  },
  {
    id: 46,
    topic: "Simplest Form & Algebra",
    prompt: "Simplify:",
    question: "\\dfrac{6}{x}\\div\\dfrac{2}{x}",
    choices: [
      { text: "3", correct: true },
      { text: "\\dfrac{1}{3}", correct: false },
      { text: "\\dfrac{12}{x^{2}}", correct: false },
      { text: "4", correct: false },
    ],
    explain: "\\(\\dfrac{6}{x}\\times\\dfrac{x}{2}=\\dfrac{6x}{2x}=3\\) (for \\(x\\neq 0\\)).",
  },
  {
    id: 47,
    topic: "Simplest Form & Algebra",
    prompt: "Translate into an algebraic expression:",
    question: "Four less than twice a number.",
    choices: [
      { text: "2x - 4", correct: true },
      { text: "4 - 2x", correct: false },
      { text: "2(x - 4)", correct: false },
      { text: "4x - 2", correct: false },
    ],
    explain: "Twice a number is \\(2x\\); four less than that is \\(2x-4\\).",
  },
  {
    id: 48,
    topic: "Simplest Form & Algebra",
    prompt: "Evaluate \\(3x + 2\\) when \\(x = -1\\).",
    question: "",
    choices: [
      { text: "-1", correct: true },
      { text: "5", correct: false },
      { text: "-5", correct: false },
      { text: "1", correct: false },
    ],
    explain: "\\(3(-1) + 2 = -3 + 2 = -1\\).",
  },
  {
    id: 49,
    topic: "Word Problem",
    prompt: "A pizza is cut into 8 equal slices. You eat \\(\\dfrac{3}{8}\\) of the pizza. How much of the pizza is left?",
    question: "",
    choices: [
      { text: "\\dfrac{5}{8}", correct: true },
      { text: "\\dfrac{3}{8}", correct: false },
      { text: "\\dfrac{1}{2}", correct: false },
      { text: "\\dfrac{8}{3}", correct: false },
    ],
    explain: "\\(1 - \\dfrac{3}{8} = \\dfrac{8}{8} - \\dfrac{3}{8} = \\dfrac{5}{8}\\).",
  },
  {
    id: 50,
    topic: "Word Problem",
    prompt: "Each bag of trail mix weighs \\(\\dfrac{3}{4}\\) pound. How many pounds do 4 bags weigh altogether?",
    question: "",
    choices: [
      { text: "3 pounds", correct: true },
      { text: "\\dfrac{3}{16} pounds", correct: false },
      { text: "4\\dfrac{3}{4} pounds", correct: false },
      { text: "\\dfrac{12}{4} pounds (not simplified)", correct: false },
    ],
    explain: "\\(\\dfrac{3}{4}\\times 4 = 3\\) pounds.",
  },
];

window.BONUS_QUESTION = {
  id: "bonus",
  topic: "Bonus",
  prompt: "Evaluate when \\(x = -2\\), \\(y = 3\\), \\(z = -1\\).",
  question: "\\dfrac{3x - 2(y + z)}{-x}",
  choices: [
    { text: "-5", correct: true },
    { text: "5", correct: false },
    { text: "-10", correct: false },
    { text: "\\dfrac{5}{2}", correct: false },
  ],
  explain:
    "Numerator: \\(3(-2) - 2(3 + (-1)) = -6 - 4 = -10\\). Denominator: \\(-(-2) = 2\\). So \\(-10 \\div 2 = -5\\).",
};
