/** Chapter 3 Practice Quiz — Set 2 (slightly easier review) */
window.QUIZ_QUESTIONS = [
  {
    id: 1,
    topic: "Fractions & Decimals",
    prompt: "Write as a decimal.",
    question: "\\dfrac{3}{4}",
    choices: [
      { text: "0.34", correct: false },
      { text: "0.75", correct: true },
      { text: "0.7", correct: false },
      { text: "0.43", correct: false },
    ],
    explain: "\\(3 \\div 4 = 0.75\\).",
  },
  {
    id: 2,
    topic: "Fractions & Decimals",
    prompt: "Write as a decimal.",
    question: "1\\dfrac{1}{2}",
    choices: [
      { text: "1.2", correct: false },
      { text: "1.5", correct: true },
      { text: "1.12", correct: false },
      { text: "0.5", correct: false },
    ],
    explain: "\\(\\dfrac{1}{2} = 0.5\\), so \\(1\\dfrac{1}{2} = 1.5\\).",
  },
  {
    id: 3,
    topic: "Fractions & Decimals",
    prompt: "Write as a fraction in simplest form.",
    question: "0.6",
    choices: [
      { text: "\\dfrac{6}{10}", correct: false },
      { text: "\\dfrac{3}{5}", correct: true },
      { text: "\\dfrac{6}{9}", correct: false },
      { text: "\\dfrac{2}{5}", correct: false },
    ],
    explain: "\\(0.6 = \\dfrac{6}{10} = \\dfrac{3}{5}\\).",
  },
  {
    id: 4,
    topic: "Fractions & Decimals",
    prompt: "Write as a mixed number in simplest form.",
    question: "2.5",
    choices: [
      { text: "2\\dfrac{5}{10}", correct: false },
      { text: "2\\dfrac{1}{2}", correct: true },
      { text: "\\dfrac{5}{2}", correct: false },
      { text: "2\\dfrac{1}{5}", correct: false },
    ],
    explain: "\\(0.5 = \\dfrac{1}{2}\\), so \\(2.5 = 2\\dfrac{1}{2}\\).",
  },
  {
    id: 5,
    topic: "Compare Numbers",
    prompt: "Write <, >, or =.",
    question: "\\dfrac{1}{2}\\quad\\_\\_\\_\\quad 0.4",
    choices: [
      { text: "<", correct: false },
      { text: ">", correct: true },
      { text: "=", correct: false },
      { text: "Cannot tell", correct: false },
    ],
    explain: "\\(\\dfrac{1}{2} = 0.5\\), and \\(0.5 > 0.4\\).",
  },
  {
    id: 6,
    topic: "Compare Numbers",
    prompt: "Write <, >, or =.",
    question: "\\dfrac{3}{4}\\quad\\_\\_\\_\\quad 0.75",
    choices: [
      { text: "<", correct: false },
      { text: ">", correct: false },
      { text: "=", correct: true },
      { text: "Cannot tell", correct: false },
    ],
    explain: "\\(\\dfrac{3}{4} = 0.75\\).",
  },
  {
    id: 7,
    topic: "True or False",
    prompt: "Determine whether the statement is true or false. If false, choose the best reason.",
    question: "\\(-3\\) is an integer.",
    choices: [
      { text: "True", correct: true },
      { text: "False — integers cannot be negative", correct: false },
      { text: "False — \\(-3\\) is only a whole number", correct: false },
      { text: "False — \\(-3\\) is a decimal", correct: false },
    ],
    explain: "Integers include ..., \\(-2\\), \\(-1\\), \\(0\\), \\(1\\), \\(2\\), .... So \\(-3\\) is an integer.",
  },
  {
    id: 8,
    topic: "True or False",
    prompt: "Determine whether the statement is true or false.",
    question: "Every integer is a whole number.",
    choices: [
      { text: "True", correct: false },
      { text: "False — negative integers are not whole numbers", correct: true },
      { text: "False — zero is not an integer", correct: false },
      { text: "False — whole numbers include fractions", correct: false },
    ],
    explain: "Whole numbers are \\(0, 1, 2, \\ldots\\). Negative integers like \\(-1\\) are integers but not whole numbers.",
  },
  {
    id: 9,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "\\dfrac{2}{3}\\times\\dfrac{3}{4}",
    choices: [
      { text: "\\dfrac{1}{2}", correct: true },
      { text: "\\dfrac{6}{12}", correct: false },
      { text: "\\dfrac{5}{7}", correct: false },
      { text: "\\dfrac{2}{4}", correct: false },
    ],
    explain: "\\(\\dfrac{2}{3}\\times\\dfrac{3}{4} = \\dfrac{6}{12} = \\dfrac{1}{2}\\).",
  },
  {
    id: 10,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "\\dfrac{3}{5}\\times\\left(-\\dfrac{1}{3}\\right)",
    choices: [
      { text: "-\\dfrac{1}{5}", correct: true },
      { text: "-\\dfrac{3}{15}", correct: false },
      { text: "\\dfrac{1}{5}", correct: false },
      { text: "-\\dfrac{4}{8}", correct: false },
    ],
    explain: "\\(\\dfrac{3}{5}\\times\\left(-\\dfrac{1}{3}\\right) = -\\dfrac{3}{15} = -\\dfrac{1}{5}\\).",
  },
  {
    id: 11,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "1\\dfrac{1}{2}\\times 2",
    choices: [
      { text: "3", correct: true },
      { text: "2\\dfrac{1}{2}", correct: false },
      { text: "\\dfrac{3}{2}", correct: false },
      { text: "4", correct: false },
    ],
    explain: "\\(\\dfrac{3}{2}\\times 2 = 3\\).",
  },
  {
    id: 12,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "\\dfrac{3}{4}\\div\\dfrac{1}{2}",
    choices: [
      { text: "\\dfrac{3}{2}", correct: true },
      { text: "\\dfrac{3}{8}", correct: false },
      { text: "\\dfrac{1}{2}", correct: false },
      { text: "2", correct: false },
    ],
    explain: "\\(\\dfrac{3}{4}\\times\\dfrac{2}{1} = \\dfrac{6}{4} = \\dfrac{3}{2}\\).",
  },
  {
    id: 13,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "2\\div\\dfrac{1}{4}",
    choices: [
      { text: "8", correct: true },
      { text: "\\dfrac{1}{2}", correct: false },
      { text: "\\dfrac{1}{8}", correct: false },
      { text: "4", correct: false },
    ],
    explain: "\\(2\\times 4 = 8\\).",
  },
  {
    id: 14,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "-\\dfrac{4}{5}\\div\\dfrac{2}{5}",
    choices: [
      { text: "-2", correct: true },
      { text: "-\\dfrac{8}{25}", correct: false },
      { text: "2", correct: false },
      { text: "-\\dfrac{2}{5}", correct: false },
    ],
    explain: "\\(-\\dfrac{4}{5}\\times\\dfrac{5}{2} = -2\\).",
  },
  {
    id: 15,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "\\dfrac{1}{4}+\\dfrac{1}{2}",
    choices: [
      { text: "\\dfrac{3}{4}", correct: true },
      { text: "\\dfrac{2}{6}", correct: false },
      { text: "\\dfrac{1}{6}", correct: false },
      { text: "\\dfrac{1}{8}", correct: false },
    ],
    explain: "LCD is 4: \\(\\dfrac{1}{4}+\\dfrac{2}{4}=\\dfrac{3}{4}\\).",
  },
  {
    id: 16,
    topic: "Add & Subtract",
    prompt: "Subtract. Simplify your answer.",
    question: "\\dfrac{5}{6}-\\dfrac{1}{3}",
    choices: [
      { text: "\\dfrac{1}{2}", correct: true },
      { text: "\\dfrac{4}{3}", correct: false },
      { text: "\\dfrac{4}{6}", correct: false },
      { text: "\\dfrac{2}{3}", correct: false },
    ],
    explain: "LCD is 6: \\(\\dfrac{5}{6}-\\dfrac{2}{6}=\\dfrac{3}{6}=\\dfrac{1}{2}\\).",
  },
  {
    id: 17,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "-\\dfrac{2}{5}+\\dfrac{1}{5}",
    choices: [
      { text: "-\\dfrac{1}{5}", correct: true },
      { text: "-\\dfrac{3}{5}", correct: false },
      { text: "\\dfrac{1}{5}", correct: false },
      { text: "-\\dfrac{1}{10}", correct: false },
    ],
    explain: "Same denominator: \\(-\\dfrac{2}{5}+\\dfrac{1}{5}=-\\dfrac{1}{5}\\).",
  },
  {
    id: 18,
    topic: "Add & Subtract",
    prompt: "Subtract. Simplify your answer.",
    question: "3\\dfrac{1}{2}-1\\dfrac{1}{4}",
    choices: [
      { text: "2\\dfrac{1}{4}", correct: true },
      { text: "2\\dfrac{1}{2}", correct: false },
      { text: "4\\dfrac{3}{4}", correct: false },
      { text: "2\\dfrac{3}{4}", correct: false },
    ],
    explain: "\\(\\dfrac{7}{2}-\\dfrac{5}{4}=\\dfrac{14}{4}-\\dfrac{5}{4}=\\dfrac{9}{4}=2\\dfrac{1}{4}\\).",
  },
  {
    id: 19,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "2\\dfrac{1}{3}+1\\dfrac{1}{3}",
    choices: [
      { text: "3\\dfrac{2}{3}", correct: true },
      { text: "3\\dfrac{1}{3}", correct: false },
      { text: "4", correct: false },
      { text: "\\dfrac{10}{3}", correct: false },
    ],
    explain: "\\(\\dfrac{7}{3}+\\dfrac{4}{3}=\\dfrac{11}{3}=3\\dfrac{2}{3}\\).",
  },
  {
    id: 20,
    topic: "Simplest Form & Algebra",
    prompt: "Which is written in simplest form?",
    question: "",
    choices: [
      { text: "\\dfrac{4}{8}", correct: false },
      { text: "\\dfrac{6}{9}", correct: false },
      { text: "\\dfrac{2}{5}", correct: true },
      { text: "\\dfrac{10}{15}", correct: false },
    ],
    explain: "A, B, and D can all be reduced. \\(\\dfrac{2}{5}\\) is already simplest.",
  },
  {
    id: 21,
    topic: "Simplest Form & Algebra",
    prompt: "Simplify:",
    question: "\\dfrac{6}{x}\\div\\dfrac{2}{x}",
    choices: [
      { text: "3", correct: true },
      { text: "\\dfrac{1}{3}", correct: false },
      { text: "\\dfrac{12}{x^{2}}", correct: false },
      { text: "4", correct: false },
    ],
    explain: "\\(\\dfrac{6}{x}\\times\\dfrac{x}{2}=\\dfrac{6x}{2x}=3\\) (for \\(x\\neq 0\\)).",
  },
  {
    id: 22,
    topic: "Simplest Form & Algebra",
    prompt: "Translate into an algebraic expression:",
    question: "Four less than twice a number.",
    choices: [
      { text: "2x - 4", correct: true },
      { text: "4 - 2x", correct: false },
      { text: "2(x - 4)", correct: false },
      { text: "4x - 2", correct: false },
    ],
    explain: "Twice a number is \\(2x\\); four less than that is \\(2x-4\\).",
  },
  {
    id: 23,
    topic: "Simplest Form & Algebra",
    prompt: "Evaluate \\(3x + 2\\) when \\(x = -1\\).",
    question: "",
    choices: [
      { text: "-1", correct: true },
      { text: "5", correct: false },
      { text: "-5", correct: false },
      { text: "1", correct: false },
    ],
    explain: "\\(3(-1) + 2 = -3 + 2 = -1\\).",
  },
  {
    id: 24,
    topic: "Word Problem",
    prompt: "A pizza is cut into 8 equal slices. You eat \\(\\dfrac{3}{8}\\) of the pizza. How much of the pizza is left?",
    question: "",
    choices: [
      { text: "\\dfrac{5}{8}", correct: true },
      { text: "\\dfrac{3}{8}", correct: false },
      { text: "\\dfrac{1}{2}", correct: false },
      { text: "\\dfrac{8}{3}", correct: false },
    ],
    explain: "\\(1 - \\dfrac{3}{8} = \\dfrac{8}{8} - \\dfrac{3}{8} = \\dfrac{5}{8}\\).",
  },
  {
    id: 25,
    topic: "Word Problem",
    prompt: "Each bag of trail mix weighs \\(\\dfrac{3}{4}\\) pound. How many pounds do 4 bags weigh altogether?",
    question: "",
    choices: [
      { text: "3 pounds", correct: true },
      { text: "\\dfrac{3}{16} pounds", correct: false },
      { text: "4\\dfrac{3}{4} pounds", correct: false },
      { text: "\\dfrac{12}{4} pounds (not simplified)", correct: false },
    ],
    explain: "\\(\\dfrac{3}{4}\\times 4 = 3\\) pounds.",
  },
];

window.BONUS_QUESTION = {
  id: "bonus",
  topic: "Bonus",
  prompt: "Evaluate when \\(x = -3\\).",
  question: "2x + 5",
  choices: [
    { text: "-1", correct: true },
    { text: "11", correct: false },
    { text: "-6", correct: false },
    { text: "1", correct: false },
  ],
  explain: "\\(2(-3) + 5 = -6 + 5 = -1\\).",
};
