/** Chapter 3 Practice Quiz — multiple-choice items with answer key */
window.QUIZ_QUESTIONS = [
  {
    id: 1,
    topic: "Fractions & Decimals",
    prompt: "Write as a decimal. Use bar notation if needed.",
    question: "\\dfrac{7}{9}",
    choices: [
      { text: "0.\\overline{7}", correct: true },
      { text: "0.79", correct: false },
      { text: "0.7", correct: false },
      { text: "0.\\overline{79}", correct: false },
    ],
    explain: "\\(7 \\div 9 = 0.777\\ldots\\), written as \\(0.\\overline{7}\\).",
  },
  {
    id: 2,
    topic: "Fractions & Decimals",
    prompt: "Write as a decimal.",
    question: "2\\dfrac{3}{8}",
    choices: [
      { text: "2.38", correct: false },
      { text: "2.375", correct: true },
      { text: "2.3\\overline{8}", correct: false },
      { text: "2.83", correct: false },
    ],
    explain: "\\(\\dfrac{3}{8} = 0.375\\), so \\(2\\dfrac{3}{8} = 2.375\\).",
  },
  {
    id: 3,
    topic: "Fractions & Decimals",
    prompt: "Write as a fraction in simplest form.",
    question: "0.45",
    choices: [
      { text: "\\dfrac{45}{100}", correct: false },
      { text: "\\dfrac{9}{20}", correct: true },
      { text: "\\dfrac{4}{5}", correct: false },
      { text: "\\dfrac{45}{99}", correct: false },
    ],
    explain: "\\(0.45 = \\dfrac{45}{100} = \\dfrac{9}{20}\\).",
  },
  {
    id: 4,
    topic: "Fractions & Decimals",
    prompt: "Write as a mixed number in simplest form.",
    question: "3.75",
    choices: [
      { text: "3\\dfrac{75}{100}", correct: false },
      { text: "3\\dfrac{3}{4}", correct: true },
      { text: "\\dfrac{15}{4}", correct: false },
      { text: "3\\dfrac{7}{5}", correct: false },
    ],
    explain: "\\(0.75 = \\dfrac{3}{4}\\), so \\(3.75 = 3\\dfrac{3}{4}\\).",
  },
  {
    id: 5,
    topic: "Compare Numbers",
    prompt: "Write <, >, or =.",
    question: "\\dfrac{5}{8}\\quad\\_\\_\\_\\quad 0.60",
    choices: [
      { text: "<", correct: false },
      { text: ">", correct: true },
      { text: "=", correct: false },
      { text: "Cannot tell", correct: false },
    ],
    explain: "\\(\\dfrac{5}{8} = 0.625\\), and \\(0.625 > 0.60\\).",
  },
  {
    id: 6,
    topic: "Compare Numbers",
    prompt: "Write <, >, or =.",
    question: "1\\dfrac{2}{5}\\quad\\_\\_\\_\\quad 1.42",
    choices: [
      { text: "<", correct: true },
      { text: ">", correct: false },
      { text: "=", correct: false },
      { text: "Cannot tell", correct: false },
    ],
    explain: "\\(1\\dfrac{2}{5} = 1.4\\), and \\(1.4 < 1.42\\).",
  },
  {
    id: 7,
    topic: "True or False",
    prompt: "Determine whether the statement is true or false. If false, choose the best reason.",
    question: "\\(-8\\) is a whole number.",
    choices: [
      { text: "True", correct: false },
      { text: "False — whole numbers are \\(0, 1, 2, \\ldots\\); negatives are not included", correct: true },
      { text: "False — \\(-8\\) is not an integer", correct: false },
      { text: "False — \\(-8\\) is a rational number only", correct: false },
    ],
    explain: "Whole numbers are non-negative integers. \\(-8\\) is an integer, but not a whole number.",
  },
  {
    id: 8,
    topic: "True or False",
    prompt: "Determine whether the statement is true or false.",
    question: "Every whole number is an integer.",
    choices: [
      { text: "True", correct: true },
      { text: "False — whole numbers include fractions", correct: false },
      { text: "False — integers do not include zero", correct: false },
      { text: "False — only positive whole numbers are integers", correct: false },
    ],
    explain: "Whole numbers are \\(0, 1, 2, \\ldots\\), and all of these are integers.",
  },
  {
    id: 9,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "\\dfrac{4}{7}\\times\\left(-\\dfrac{14}{15}\\right)",
    choices: [
      { text: "-\\dfrac{8}{15}", correct: true },
      { text: "-\\dfrac{56}{105}", correct: false },
      { text: "\\dfrac{8}{15}", correct: false },
      { text: "-\\dfrac{2}{3}", correct: false },
    ],
    explain: "\\(\\dfrac{4}{7}\\times\\left(-\\dfrac{14}{15}\\right) = -\\dfrac{56}{105} = -\\dfrac{8}{15}\\).",
  },
  {
    id: 10,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "2\\dfrac{1}{4}\\times\\left(-1\\dfrac{1}{3}\\right)",
    choices: [
      { text: "-3", correct: true },
      { text: "-\\dfrac{9}{4}", correct: false },
      { text: "3", correct: false },
      { text: "-\\dfrac{3}{4}", correct: false },
    ],
    explain: "\\(\\dfrac{9}{4}\\times\\left(-\\dfrac{4}{3}\\right) = -3\\).",
  },
  {
    id: 11,
    topic: "Multiply",
    prompt: "Multiply. Simplify your answer.",
    question: "-3\\dfrac{1}{2}\\times 2\\dfrac{2}{7}",
    choices: [
      { text: "-8", correct: true },
      { text: "-7", correct: false },
      { text: "8", correct: false },
      { text: "-\\dfrac{16}{2}", correct: false },
    ],
    explain: "\\(-\\dfrac{7}{2}\\times\\dfrac{16}{7} = -8\\).",
  },
  {
    id: 12,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "3\\dfrac{3}{4}\\div\\dfrac{5}{8}",
    choices: [
      { text: "6", correct: true },
      { text: "\\dfrac{15}{4}", correct: false },
      { text: "\\dfrac{24}{5}", correct: false },
      { text: "\\dfrac{5}{6}", correct: false },
    ],
    explain: "\\(\\dfrac{15}{4}\\times\\dfrac{8}{5} = 6\\).",
  },
  {
    id: 13,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "-2\\dfrac{2}{3}\\div 1\\dfrac{1}{3}",
    choices: [
      { text: "-2", correct: true },
      { text: "-\\dfrac{8}{3}", correct: false },
      { text: "2", correct: false },
      { text: "-\\dfrac{1}{2}", correct: false },
    ],
    explain: "\\(-\\dfrac{8}{3}\\div\\dfrac{4}{3} = -\\dfrac{8}{3}\\times\\dfrac{3}{4} = -2\\).",
  },
  {
    id: 14,
    topic: "Divide",
    prompt: "Divide. Simplify your answer.",
    question: "\\dfrac{7}{12}\\div\\left(-\\dfrac{14}{9}\\right)",
    choices: [
      { text: "-\\dfrac{3}{8}", correct: true },
      { text: "-\\dfrac{7}{8}", correct: false },
      { text: "\\dfrac{3}{8}", correct: false },
      { text: "-\\dfrac{98}{108}", correct: false },
    ],
    explain: "\\(\\dfrac{7}{12}\\times\\left(-\\dfrac{9}{14}\\right) = -\\dfrac{3}{8}\\).",
  },
  {
    id: 15,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "-\\dfrac{3}{8}+\\left(-\\dfrac{5}{6}\\right)",
    choices: [
      { text: "-1\\dfrac{5}{24}", correct: true },
      { text: "-\\dfrac{8}{14}", correct: false },
      { text: "-\\dfrac{29}{48}", correct: false },
      { text: "\\dfrac{29}{24}", correct: false },
    ],
    explain: "LCD is 24: \\(-\\dfrac{9}{24}+\\left(-\\dfrac{20}{24}\\right)=-\\dfrac{29}{24}=-1\\dfrac{5}{24}\\).",
  },
  {
    id: 16,
    topic: "Add & Subtract",
    prompt: "Subtract. Simplify your answer.",
    question: "4\\dfrac{2}{5}-1\\dfrac{3}{10}",
    choices: [
      { text: "3\\dfrac{1}{10}", correct: true },
      { text: "3\\dfrac{1}{5}", correct: false },
      { text: "2\\dfrac{9}{10}", correct: false },
      { text: "3\\dfrac{5}{10}", correct: false },
    ],
    explain: "\\(\\dfrac{44}{10}-\\dfrac{13}{10}=\\dfrac{31}{10}=3\\dfrac{1}{10}\\).",
  },
  {
    id: 17,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "-3\\dfrac{1}{4}+2\\dfrac{2}{3}",
    choices: [
      { text: "-\\dfrac{7}{12}", correct: true },
      { text: "-\\dfrac{5}{12}", correct: false },
      { text: "\\dfrac{7}{12}", correct: false },
      { text: "-1\\dfrac{5}{12}", correct: false },
    ],
    explain: "\\(-\\dfrac{13}{4}+\\dfrac{8}{3}=-\\dfrac{39}{12}+\\dfrac{32}{12}=-\\dfrac{7}{12}\\).",
  },
  {
    id: 18,
    topic: "Add & Subtract",
    prompt: "Subtract. Simplify your answer.",
    question: "-2\\dfrac{5}{6}-3\\dfrac{1}{4}",
    choices: [
      { text: "-6\\dfrac{1}{12}", correct: true },
      { text: "-5\\dfrac{1}{12}", correct: false },
      { text: "-\\dfrac{73}{24}", correct: false },
      { text: "6\\dfrac{1}{12}", correct: false },
    ],
    explain: "\\(-\\dfrac{17}{6}-\\dfrac{13}{4}=-\\dfrac{34}{12}-\\dfrac{39}{12}=-\\dfrac{73}{12}=-6\\dfrac{1}{12}\\).",
  },
  {
    id: 19,
    topic: "Add & Subtract",
    prompt: "Add. Simplify your answer.",
    question: "5\\dfrac{3}{8}+\\left(-2\\dfrac{1}{2}\\right)",
    choices: [
      { text: "2\\dfrac{7}{8}", correct: true },
      { text: "3\\dfrac{1}{8}", correct: false },
      { text: "2\\dfrac{1}{8}", correct: false },
      { text: "7\\dfrac{7}{8}", correct: false },
    ],
    explain: "\\(\\dfrac{43}{8}-\\dfrac{20}{8}=\\dfrac{23}{8}=2\\dfrac{7}{8}\\).",
  },
  {
    id: 20,
    topic: "Simplest Form & Algebra",
    prompt: "Which is written in simplest form?",
    question: "",
    choices: [
      { text: "\\dfrac{18}{24}", correct: false },
      { text: "\\dfrac{14}{21}", correct: false },
      { text: "3\\dfrac{5}{8}", correct: true },
      { text: "\\dfrac{16}{20}", correct: false },
    ],
    explain: "A, B, and D can all be reduced. \\(3\\dfrac{5}{8}\\) is already simplest.",
  },
  {
    id: 21,
    topic: "Simplest Form & Algebra",
    prompt: "Simplify:",
    question: "\\dfrac{4}{x}\\div\\dfrac{8}{3x}",
    choices: [
      { text: "\\dfrac{3}{2}", correct: true },
      { text: "\\dfrac{1}{2}", correct: false },
      { text: "\\dfrac{32}{3x^{2}}", correct: false },
      { text: "\\dfrac{3x}{2}", correct: false },
    ],
    explain: "\\(\\dfrac{4}{x}\\times\\dfrac{3x}{8}=\\dfrac{12x}{8x}=\\dfrac{3}{2}\\) (for \\(x\\neq 0\\)).",
  },
  {
    id: 22,
    topic: "Simplest Form & Algebra",
    prompt: "Translate into an algebraic expression:",
    question: "Five more than the product of negative three and a number.",
    choices: [
      { text: "-3x + 5", correct: true },
      { text: "5 - 3 + x", correct: false },
      { text: "-3(x + 5)", correct: false },
      { text: "5x - 3", correct: false },
    ],
    explain: "Product of \\(-3\\) and a number is \\(-3x\\); five more than that is \\(-3x+5\\).",
  },
  {
    id: 23,
    topic: "Simplest Form & Algebra",
    prompt: "Evaluate \\(2x - 3y\\) when \\(x = -4\\) and \\(y = 2\\).",
    question: "",
    choices: [
      { text: "-14", correct: true },
      { text: "-2", correct: false },
      { text: "2", correct: false },
      { text: "-10", correct: false },
    ],
    explain: "\\(2(-4) - 3(2) = -8 - 6 = -14\\).",
  },
  {
    id: 24,
    topic: "Word Problem",
    prompt: "A recipe requires \\(\\dfrac{3}{4}\\) cup of sugar for one batch. If you make 3 batches, how many cups of sugar are needed?",
    question: "",
    choices: [
      { text: "2\\dfrac{1}{4} cups", correct: true },
      { text: "\\dfrac{3}{4} cups", correct: false },
      { text: "3\\dfrac{3}{4} cups", correct: false },
      { text: "\\dfrac{9}{12} cups", correct: false },
    ],
    explain: "\\(\\dfrac{3}{4}\\times 3 = \\dfrac{9}{4} = 2\\dfrac{1}{4}\\) cups.",
  },
  {
    id: 25,
    topic: "Word Problem",
    prompt: "A runner runs \\(2\\dfrac{1}{2}\\) miles each day for 4 days. How many miles does the runner run altogether?",
    question: "",
    choices: [
      { text: "10 miles", correct: true },
      { text: "6\\dfrac{1}{2} miles", correct: false },
      { text: "8 miles", correct: false },
      { text: "\\dfrac{5}{2} miles", correct: false },
    ],
    explain: "\\(2\\dfrac{1}{2}\\times 4 = \\dfrac{5}{2}\\times 4 = 10\\) miles.",
  },
];

window.BONUS_QUESTION = {
  id: "bonus",
  topic: "Bonus",
  prompt: "Evaluate when \\(x = -2\\), \\(y = 3\\), \\(z = -1\\).",
  question: "\\dfrac{3x - 2(y + z)}{-x}",
  choices: [
    { text: "-5", correct: true },
    { text: "5", correct: false },
    { text: "-10", correct: false },
    { text: "\\dfrac{5}{2}", correct: false },
  ],
  explain:
    "Numerator: \\(3(-2) - 2(3 + (-1)) = -6 - 4 = -10\\). Denominator: \\(-(-2) = 2\\). So \\(-10 \\div 2 = -5\\).",
};
